title: Status @ Bergen-IT
languageCode: de
params:
  copyrightHolder: Bergen-IT // Timo Bergen
  dateFormat: '2. Januar, 2006 at 15:04'
  description_footer: ''
  description_header: ''
  eventsPerPage: 10
  logo: /images/clearstatus.svg
  meta_description: Statusseite der Bergen-IT Infrastruktur
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Unsere Firmen-Webseite
      link: 'https://bergen-it.net'
      name: Website
    - description: ''
      link: ''
      name: Mailserver Node B
    - name: Mailserver Node F
    - name: Apache Proxy Node H1
    - name: Apache Proxy Node C1
  timezoneString: ' UTC'
